#spring.application.name=Journals
#
#spring.data.mongodb.database=journals_db
#spring.data.mongodb.uri=${MONGODB_URI}
#spring.data.mongodb.auto-index-creation=true


spring:
  application:
    name: Journals
  data:
    mongodb:
      database: journals_db
      uri: ${MONGODB_URI}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: abdulkanoor@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080
  servlet:
    context-path: /journal


weather:
  api:
    key: ba9f80960815791caa42e03930c0613d


quotes:
  api:
    url: https://dummyjson.com

